version: '3.8'

services:
  db:
    image: 'postgres:14-alpine'
    hostname: 'postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgresql'
      POSTGRES_DB: 'xetia'
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data

  redis:
    image: 'redis:7-alpine'
    hostname: 'redis'
    ports:
      - 6379:6379

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    hostname: 'rabbitmq'
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: boilerplate
      RABBITMQ_DEFAULT_PASS: 6yalTW5anImUSmJc
      RABBITMQ_DEFAULT_VHOST: "/local"

volumes:
  pgdata:
